version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todo
      MYSQL_PASSWORD: todopass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/init.sql